stages:
  # - install
  # - frontend-lint
  # - backend-lint
  - build
  - deploy


before_script:
  # - eval `ssh-agent -s`
  # - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - git submodule sync --recursive
  - git submodule update --init --recursive

# job_frontend_lint:
#   stage: frontend-lint
#   script:
#     - cd /unilab-frontend
#     - 

job_build:
  tags:
    - unilab-deploy
  stage: build
  script:
    - make build

job_deploy:
  tags:
    - unilab-deploy
  stage: deploy
  script:
    - make deploy
