# how to pull submodules or other git repos in gitlab-runner ?
# see: https://docs.gitlab.com/ee/ci/ssh_keys/#ssh-keys-when-using-the-shell-executor
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  # - install
  # - frontend-lint
  # - backend-lint
  - build
  - deploy

# job_frontend_lint:
#   stage: frontend-lint
#   script:
#     - cd /unilab-frontend
#     - 

job_build:
  tags:
    - unilab-deploy
  stage: build
  script:
    - make build

job_deploy:
  tags:
    - unilab-deploy
  stage: deploy
  script:
    - make deploy
