version: '3.8'
# version see: https://docs.docker.com/compose/compose-file/compose-versioning/
services:

  unilab-nginx:
    container_name: unilab-nginx
    build: ./unilab-frontend
    restart: always
    depends_on: 
      - unilab-backend1
      - unilab-backend2
      - unilab-backend3
    networks: 
      - frontend
      - backend
    ports: 
      - 8080:80
    environment:
      TZ: 'Asia/Shanghai'
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /home/cslab/unilab-mount/nginx/logs:/var/log/nginx

  unilab-mysql:
    container_name: unilab-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: unilab
      MYSQL_USER: unilab
      MYSQL_PASSWORD: 123456
      TZ: 'Asia/Shanghai'
    ports: 
      - 3307:3306
    networks:
      backend:
        aliases:
          - mysql
    volumes: 
      - /home/cslab/unilab-mount/mysql/data:/var/lib/mysql
      - /home/cslab/unilab-mount/mysql/backup:/tmp/mysql-backup
      - /home/cslab/unilab-mount/mysql/logs:/var/log/mysql
      - ./mysql/init/:/docker-entrypoint-initdb.d/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - /etc/localtime:/etc/localtime:ro
    command:
      --authentication-policy=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    healthcheck:
      test: '/usr/bin/mysql --user=unilab --password=123456 --execute "SHOW DATABASES;"'
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 10s

  unilab-redis:
    container_name: unilab-redis
    image: redis:latest
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: 'Asia/Shanghai'
    ports:
      - 6380:6379
    networks:
      backend:
        aliases:
          - redis
    volumes:
      - /home/cslab/unilab-mount/redis/data:/var/lib/redis:rw
      - /home/cslab/unilab-mount/redis/log:/var/log/redis:rw
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:rw
    command:
      /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf --requirepass 123456"
    healthcheck:
      test: "redis-cli ping -h 127.0.0.1 -p 6379 -a 123456"
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 5s
  
  unilab-backend1:
    container_name: unilab-backend1
    build: ./unilab-backend
    depends_on:
      unilab-mysql:
        condition: service_healthy
      unilab-redis:
        condition: service_healthy
    restart: always
    networks:
      - backend
    volumes: 
      - /home/cslab/unilab-mount/server1-runtime:/unilab-files/runtime
      - /home/cslab/unilab-mount/upload:/unilab-files/upload:rw
    cap_add:
     - SYS_PTRACE

  unilab-backend2:
    container_name: unilab-backend2
    build: ./unilab-backend
    depends_on:
      unilab-mysql:
        condition: service_healthy
      unilab-redis:
        condition: service_healthy
    restart: always
    networks:
      - backend
    volumes: 
      - /home/cslab/unilab-mount/server2-runtime:/unilab-files/runtime
      - /home/cslab/unilab-mount/upload:/unilab-files/upload:rw
    cap_add:
     - SYS_PTRACE
      
  unilab-backend3:
    container_name: unilab-backend3
    build: ./unilab-backend
    depends_on:
      unilab-mysql:
        condition: service_healthy
      unilab-redis:
        condition: service_healthy
    restart: always
    networks:
      - backend
    volumes: 
      - /home/cslab/unilab-mount/server3-runtime:/unilab-files/runtime
      - /home/cslab/unilab-mount/upload:/unilab-files/upload:rw
    cap_add:
     - SYS_PTRACE


networks:
  frontend:
  backend:
