version: '3.8'
# version see: https://docs.docker.com/compose/compose-file/compose-versioning/
services:

  unilab-nginx:
    container_name: unilab-nginx
    build: ./unilab-frontend
    restart: always
    depends_on: 
      - unilab-backend1
      - unilab-backend2
      - unilab-backend3
    networks: 
      - frontend
      - backend
    ports: 
      - 8080:80
    environment:
      TZ: 'Asia/Shanghai'
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /home/cslab/unilab-mount/nginx/logs:/var/log/nginx

  unilab-mysql:
    container_name: unilab-mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: unilab
      TZ: 'Asia/Shanghai'
    ports: 
      - 3307:3306
    networks:
      backend:
        aliases:
          - mysql
    volumes: 
      - /home/cslab/unilab-mount/mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d/
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=123456 --execute "SHOW DATABASES;"'
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 15s

  unilab-backend1:
    container_name: unilab-backend1
    build: ./unilab-backend
    depends_on:
      unilab-mysql:
        condition: service_healthy
    restart: always
    networks:
      - backend
    volumes: 
      - /home/cslab/unilab-mount/server1-runtime:/unilab-files/runtime
      - /home/cslab/unilab-mount/upload:/unilab-files/upload:rw
    cap_add:
     - SYS_PTRACE

  unilab-backend2:
    container_name: unilab-backend2
    build: ./unilab-backend
    depends_on:
      unilab-mysql:
        condition: service_healthy
    restart: always
    networks:
      - backend
    volumes: 
      - /home/cslab/unilab-mount/server2-runtime:/unilab-files/runtime
      - /home/cslab/unilab-mount/upload:/unilab-files/upload:rw
    cap_add:
     - SYS_PTRACE
      
  unilab-backend3:
    container_name: unilab-backend3
    build: ./unilab-backend
    depends_on:
      unilab-mysql:
        condition: service_healthy
    restart: always
    networks:
      - backend
    volumes: 
      - /home/cslab/unilab-mount/server3-runtime:/unilab-files/runtime
      - /home/cslab/unilab-mount/upload:/unilab-files/upload:rw
    cap_add:
     - SYS_PTRACE


networks:
  frontend:
  backend:
